{{- if and (eq .Values.config.executionsMode "queue") .Values.queue.redis.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n.fullname" . }}-queue
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
type: Opaque
stringData:
  QUEUE_BULL_REDIS_PASSWORD: {{ .Values.queue.redis.password | quote }}
{{- end }}
