apiVersion: v2
name: n8n
description: Helm chart for n8n workflow automation
type: application
version: 0.3.1
appVersion: "2.35.7"
keywords:
  - n8n
  - workflow
  - automation
  - low-code
sources:
  - https://github.com/n8n-io/n8n
home: https://n8n.io
maintainers:
  - name: crazyuploader
    url: https://github.com/crazyuploader
annotations:
  artifacthub.io/repo-id: 77d03ad2-ee36-42fc-9f19-0856b1bab276
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: n8n docs
      url: https://docs.n8n.io
    - name: source
      url: https://github.com/crazyuploader/helm-charts/tree/main/charts/n8n
  artifacthub.io/changes: |
    - Update Daytona sandbox image to 0.10.0
